### ISSUE TITLE
关于您的版本的简体中文版.

### ISSUE THREAD

**Issue by PandaDecSt** [kurtyu/PixelDungeonTC#1]
你好, 我对您源码的字库改成了简体中文的样式, 
并且使源码能够在手机AIDE上正常编译运行, 
我发出此问题是想要得到您的授权, 以方便我能够开放源代码.
希望您可以同意.

**Comment by kurtyu** [comment]
您好～
完全沒問題
關於源代碼字庫的修改與編輯的部份
我同意授權並開放源代碼
如果需要請註記來源即可

謝謝您的告知


Xi-You <notifications@github.com> 於 2020年11月7日 週六 下午9:37寫道：

**Comment by PandaDecSt** [comment]
感谢授权!😊
简体中文开源项目在[这里](https://github.com/Xi-You/PixelDungeon-CH).
