### ISSUE TITLE
奇怪的READ_PHONE_STATE权限

### ISSUE THREAD

**Issue by PandaDecSt** [kurtyu/PixelDungeonTC#3]
我将您的源码编译后发现应用需要 获取设备状态android.permission.READ_PHONE_STATE 的权限
将项目安卓分支代码重写清理后编译后发现还是有这个权限(AndroidManifest.xml也修改了)
这很奇怪 所以最后我没办法了只能来问一下您 希望问题能够得到解决

**Comment by kurtyu** [comment]
請把Google Analytics 移除試試看
// compile 'com.google.android.gms:play-services-analytics:10.2.1'

Xi-You <notifications@github.com> 於 2020年11月25日 週三 下午9:11寫道：

**Comment by PandaDecSt** [comment]
感谢回复 我已经找到了大概的原因 应该是因为新版libgdx需要这个权限
